### login
POST http://localhost:5000/login
Accept: */*
Content-Type: application/json

{
  "userName": "rwribeiro",
  "password": "123"
}

### create user
POST http://localhost:5000/user
Accept: */*
Content-Type: application/json

{
  "Login": "teste",
  "password": "123"
}

### list users
GET http://rafaelwilliam.com.br:5000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImFkbWluIiwibmJmIjoxNjkyNDc5NzIyLCJleHAiOjE2OTI1MDg1MjIsImlhdCI6MTY5MjQ3OTcyMn0.qkxGRTrVTXoX4DTGv9Ewn57wLpBvT1J8VPlqo-jwNvg