GET http://localhost:5211/category
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImxvZ2luIiwibmJmIjoxNjgyNzkxNTk3LCJleHAiOjE2ODI4MjAzOTcsImlhdCI6MTY4Mjc5MTU5N30.qPJoXTcJKyvyEdg3b7J7_hP1jao6GqYUXX7uYkvKDkQ

###
DELETE  http://localhost:5211/category/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImxvZ2luIiwibmJmIjoxNjgyNzkxNTk3LCJleHAiOjE2ODI4MjAzOTcsImlhdCI6MTY4Mjc5MTU5N30.qPJoXTcJKyvyEdg3b7J7_hP1jao6GqYUXX7uYkvKDkQ

###
POST  http://localhost:5211/category
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImxvZ2luIiwibmJmIjoxNjgyNzkxNTk3LCJleHAiOjE2ODI4MjAzOTcsImlhdCI6MTY4Mjc5MTU5N30.qPJoXTcJKyvyEdg3b7J7_hP1jao6GqYUXX7uYkvKDkQ
Content-Type: application/json

{
    "Name": "CUSTOS FIXOS"
}