### GET ALL MOVEMENTS
GET http://localhost:5211/movement/1007
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImxvZ2luIiwibmJmIjoxNjgyOTgyMjQyLCJleHAiOjE2ODMwMTEwNDIsImlhdCI6MTY4Mjk4MjI0Mn0.obDxQOzg9whxwmbMvALMkGYtoW3AryX693Dq9sua1Kw

### NEW MOVEMENT
POST http://localhost:5211/movement
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImxvZ2luIiwibmJmIjoxNjgyOTgyMjQyLCJleHAiOjE2ODMwMTEwNDIsImlhdCI6MTY4Mjk4MjI0Mn0.obDxQOzg9whxwmbMvALMkGYtoW3AryX693Dq9sua1Kw
Content-Type: application/json

{
  "date": "2023-05-01T23:05:27.297Z",
  "value": 5.98,
  "description": "MXRF11",
  "categoryId": 7
}

###
# 0 - credit
# 1 - debit
### EDIT
PUT http://localhost:5211/movement
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImxvZ2luIiwibmJmIjoxNjgyOTgyMjQyLCJleHAiOjE2ODMwMTEwNDIsImlhdCI6MTY4Mjk4MjI0Mn0.obDxQOzg9whxwmbMvALMkGYtoW3AryX693Dq9sua1Kw
Content-Type: application/json

{
  "id": 1007,
  "date": "2023-05-01T23:05:27.297",
  "value": 5.97,
  "description": "[FII] MXRF11",
  "categoryId": 7
}