### GET ALL MOVEMENTS
GET http://localhost:5211/movement/1006
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImxvZ2luIiwibmJmIjoxNjgyOTYzNDM2LCJleHAiOjE2ODI5OTIyMzYsImlhdCI6MTY4Mjk2MzQzNn0.wC_4qhABpqNBcRDvO65qzYqR2-WIglg0y_Y9JpclbB8

### NEW MOVEMENT
POST http://localhost:5211/movement
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImxvZ2luIiwibmJmIjoxNjgyOTYzNDM2LCJleHAiOjE2ODI5OTIyMzYsImlhdCI6MTY4Mjk2MzQzNn0.wC_4qhABpqNBcRDvO65qzYqR2-WIglg0y_Y9JpclbB8
Content-Type: application/json

{
  "date": "2023-05-01T17:51:27.297Z",
  "value": 10,
  "description": "Coca cola",
  "type": 1,
  "categoryId": 3,
  "userId": 2
}

###
# 0 - credit
# 1 - debit
### EDIT
PUT http://localhost:5211/movement
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImxvZ2luIiwibmJmIjoxNjgyOTYzNDM2LCJleHAiOjE2ODI5OTIyMzYsImlhdCI6MTY4Mjk2MzQzNn0.wC_4qhABpqNBcRDvO65qzYqR2-WIglg0y_Y9JpclbB8
Content-Type: application/json

{
  "id": 1006,
  "date": "2023-05-01T17:51:27.297Z",
  "value": 80,
  "description": "Futebas na praça",
  "type": 1,
  "categoryId": 3
}