### GENERATE TOKEN
POST http://localhost:5211/login
Content-Type: application/json

{
    "UserName": "string",
    "password": "string"
}

### GET ALL USER
GET http://localhost:5211/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InN0cmluZyIsIm5iZiI6MTY4MjQ0MTMwNywiZXhwIjoxNjgyNDcwMTA3LCJpYXQiOjE2ODI0NDEzMDd9.p1q9PqKmn2FFf3S6OKZJ7M2-pt27NJOk6GOOQ_ZSnMk

### POST
### eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InN0cmluZyIsIm5iZiI6MTY4MjI5NTQ1NSwiZXhwIjoxNjgyMzI0MjU1LCJpYXQiOjE2ODIyOTU0NTV9.RSYe7Ewh4bjAKoQaMys9-F-4d8NFGVLJMBq6YkJlHLU
POST http://localhost:5211/user
Content-Type: application/json

{

    "login": "aaa",
    "password": "aaa"
}


### GET ALL MOVEMENTS
GET http://localhost:5211/movement
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InN0cmluZyIsIm5iZiI6MTY4MjQ0MTMwNywiZXhwIjoxNjgyNDcwMTA3LCJpYXQiOjE2ODI0NDEzMDd9.p1q9PqKmn2FFf3S6OKZJ7M2-pt27NJOk6GOOQ_ZSnMk


