### GENERATE TOKEN
POST http://localhost:5000/login
Content-Type: application/json

{
    "UserName": "admin",
    "password": "admin"
}

### GET ALL USER
GET http://localhost:5000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InJ3cmliZWlybyIsIm5iZiI6MTY4OTEyNzgxNSwiZXhwIjoxNjg5MTU2NjE1LCJpYXQiOjE2ODkxMjc4MTV9.gEl1hdHWOww_1yRy8PiQzIF4NbrDn8TdZ0TvGZu5HBg

### POST
### eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InN0cmluZyIsIm5iZiI6MTY4MjI5NTQ1NSwiZXhwIjoxNjgyMzI0MjU1LCJpYXQiOjE2ODIyOTU0NTV9.RSYe7Ewh4bjAKoQaMys9-F-4d8NFGVLJMBq6YkJlHLU
POST http://localhost:5211/user
Content-Type: application/json

{
    "login": "aaa",
    "password": "aaa"
}

### DELETE
DELETE http://localhost:5211/user/2005
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InN0cmluZyIsIm5iZiI6MTY4MjQ3Mzg5NCwiZXhwIjoxNjgyNTAyNjk0LCJpYXQiOjE2ODI0NzM4OTR9.yMSlvbMktuxTJ4VjtJ1CMyCOkxqN3NdsBldalbyCUQk
Content-Type: application/json


### UPDATE USER
PUT http://localhost:5211/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InN0cmluZyIsIm5iZiI6MTY4MjQ3Mzg5NCwiZXhwIjoxNjgyNTAyNjk0LCJpYXQiOjE2ODI0NzM4OTR9.yMSlvbMktuxTJ4VjtJ1CMyCOkxqN3NdsBldalbyCUQk

{
    "id": 5,
    "login": "login",
    "password": "xxx"
}
